### ISSUE TITLE
Image tracking Unity EntryPointNotFoundException

### ISSUE THREAD

**Issue by jordystoltenbarg** [zappar-xr/unity-example-image-tracking-3d-animation#1]
Hello all,

I'm testing my WebGl build with image tracking but I keep having this same error no matter what I do (even removed my Zappar folder and copied from the image tracking example). Even though I have this error the image tracking does still seem to work correctly.

I hope someone is able to help.

EntryPointNotFoundException: zappar_image_tracker_target_preview_rgba_width
Zappar.Z.ImageTrackerTargetPreviewRgbaWidth (System.IntPtr o, System.Int32 indx) (at Assets/Zappar/Scripts/Z.cs:971)
ZapparEditModeImageTarget.SetupImagePreview () (at Assets/Zappar/Scripts/ZapparEditModeImageTarget.cs:57)
ZapparEditModeImageTarget.TargetDataAvailableCallback (System.Byte[] data) (at Assets/Zappar/Scripts/ZapparEditModeImageTarget.cs:92)
Zappar.Z+<LoadZPTTarget>d__140.MoveNext () (at Assets/Zappar/Scripts/Z.cs:551)

**Comment by nfynt-zap** [comment]
If I remember correctly this issue was particular to Unity windows editor and since has been fixed. 

Do checkout the newer release of UAR and examples repo.

Cheers,
